name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: avimehndi/strapi-app
    
    outputs:
      image_tag: ${{ steps.tag.outputs.tag }}
      full_image: ${{ steps.tag.outputs.full_image }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Docker Tag
        id: tag
        run: |
          TAG=$(git rev-parse --short HEAD)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "full_image=${{ env.IMAGE_NAME }}:$TAG" >> $GITHUB_OUTPUT

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./my_strapi_project
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}

      - name: Save Docker image tag as artifact
        run: echo "${{ steps.tag.outputs.tag }}" > docker_tag.txt

      - name: Upload Docker Tag Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-tag
          path: docker_tag.txt
