name: CD - Deploy with Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Docker tag artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ci.yml
          workflow_conclusion: success
          name: docker-tag
          path: ./artifacts
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Docker Tag
        id: tag
        run: |
          TAG=$(cat ./artifacts/docker_tag.txt)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="docker_image_tag=${{ steps.tag.outputs.tag }}" \
            -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Output EC2 Instance Details
        run: |
          echo "EC2 Public IP: $(terraform output -raw ec2_public_ip)"
          echo "Strapi URL: http://$(terraform output -raw ec2_public_ip):1337"
